{
 "title": "sese-engine",
 "time": { "from": "now-24h", "to": "now" },
 "refresh": "30s",
 "panels": [
  { "title": "收获服务器", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "内存行数",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "locale" } },
   "targets": [
    { "expr": "nei_cun_xing_shu", "legendFormat": "存储" },
    {
     "expr": "sum(nei_cun_xing_shu_ma_ke_si) > 0",
     "legendFormat": "存储上限"
    },
    { "expr": "sum(diu_qi_xing_shu)", "legendFormat": "丢弃" }
   ]
  },
  {
   "title": "内存行数-进度",
   "type": "piechart",
   "gridPos": { "h": 6, "w": 4, "x": 8, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "locale" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "sum(nei_cun_xing_shu)", "legendFormat": "当前" },
    {
     "expr": "clamp_min(sum(nei_cun_xing_shu_ma_ke_si) - sum(nei_cun_xing_shu), 0)",
     "legendFormat": "剩余"
    }
   ]
  },
  {
   "title": "大清洗-词数",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 12, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "locale" } },
   "targets": [
    { "expr": "da_qing_xi", "legendFormat": "当前" },
    { "expr": "sum(da_qing_xi_ma_ke_si) > 0", "legendFormat": "上限" }
   ]
  },
  {
   "title": "大清洗-进度",
   "type": "piechart",
   "gridPos": { "h": 6, "w": 4, "x": 20, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "locale" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "sum(da_qing_xi)", "legendFormat": "当前" },
    {
     "expr": "sum(da_qing_xi_ma_ke_si) - sum(da_qing_xi)",
     "legendFormat": "剩余"
    }
   ]
  },
  {
   "title": "内存行数-预期剩余时间",
   "type": "stat",
   "gridPos": { "h": 2, "w": 4, "x": 8, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "clamp_min((sum(nei_cun_xing_shu_ma_ke_si) - sum(nei_cun_xing_shu)) / deriv(sum(nei_cun_xing_shu)[5m:]) - 60, 0)",
     "legendFormat": "当前"
    }
   ]
  },
  {
   "title": "大清洗-预期剩余时间",
   "type": "stat",
   "gridPos": { "h": 2, "w": 4, "x": 20, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "clamp_min((sum(da_qing_xi_ma_ke_si) - sum(da_qing_xi)) / deriv(sum(da_qing_xi)[20m:]) - 60, 0)",
     "legendFormat": "当前"
    }
   ]
  },
  {
   "title": "内存键数",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "locale" } },
   "targets": [
    { "expr": "nei_cun_jian_shu", "legendFormat": "总数" }
   ]
  },
  {
   "title": "大清洗-索引总行数",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "locale" } },
   "targets": [
    { "expr": "da_qing_xi_suo_yin_shu", "legendFormat": "总数" }
   ]
  },
  {
   "title": "收到请求数",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 17 },
   "fieldConfig": { "defaults": { "unit": "locale" } },
   "targets": [
    { "expr": "shou_dao_qing_qiu_shu", "legendFormat": "总数" }
   ]
  },
  {
   "title": "大清洗-平均每个词新增了几行",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 17 },
   "targets": [
    {
     "expr": "delta(da_qing_xi_suo_yin_shu[10m]) / delta(da_qing_xi[10m]) > 0",
     "legendFormat": "总数"
    }
   ]
  },
  {
   "title": "索引行数分布",
   "type": "heatmap",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 25 },
   "targets": [
    {
     "expr": "sum by (le) (rate(suo_yin_xing_shu_bucket[$__rate_interval]))",
     "legendFormat": "{{le}}"
    }
   ]
  },
  {
   "title": "索引增加行数分布",
   "type": "heatmap",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 25 },
   "targets": [
    {
     "expr": "sum by (le) (rate(suo_yin_zeng_jia_xing_shu_da_dian_bucket[$__rate_interval]))",
     "legendFormat": "{{le}}"
    }
   ]
  },
  { "title": "爬虫", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 32 } },
  {
   "title": "Epoch",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 33 },
   "targets": [
    { "expr": "sum(epoch)", "legendFormat": "当前" },
    { "expr": "sum(epoch_ma_ke_si) > 0", "legendFormat": "上限" }
   ]
  },
  {
   "title": "当前Epoch进度",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 33 },
   "targets": [
    { "expr": "sum(dang_qian_epoch_jin_du)", "legendFormat": "当前" },
    {
     "expr": "sum(dang_qian_epoch_jin_du_ma_ke_si)",
     "legendFormat": "上限"
    }
   ]
  },
  {
   "title": "每秒访问url个数",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 41 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "sum(rate(fang_wen_url_shu[$__rate_interval]))",
     "legendFormat": "总共"
    },
    {
     "expr": "sum(rate(fang_wen_cheng_gong_url_shu[$__rate_interval]))",
     "legendFormat": "成功"
    }
   ]
  },
  {
   "title": "每秒获取词个数",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 41 },
   "fieldConfig": { "defaults": { "unit": "string" } },
   "targets": [
    {
     "expr": "sum(rate(huo_qu_ci_shu[$__rate_interval]))",
     "legendFormat": "总共"
    },
    {
     "expr": "sum(rate(huo_qu_ci_shu___ying_wen__[$__rate_interval]))",
     "legendFormat": "英文"
    }
   ]
  },
  {
   "title": "每秒获取域名基本信息个数",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 50 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "sum(rate(huo_qu_yu_ming_ji_ben_xin_xi_ci_shu[$__rate_interval]))",
     "legendFormat": "总共"
    }
   ]
  },
  {
   "title": "处理单个url耗时分布 (下载+分析+存储)",
   "type": "heatmap",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 50 },
   "targets": [
    {
     "expr": "sum by (le) (rate(zhai_time_bucket[$__rate_interval]))",
     "legendFormat": "{{le}}"
    }
   ]
  },
  {
   "title": "访问url繁荣分布",
   "type": "heatmap",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 59 },
   "targets": [
    {
     "expr": "sum by (le) (rate(fang_wen_url_fan_rong_bucket[$__rate_interval]))",
     "legendFormat": "{{le}}"
    }
   ]
  },
  {
   "title": "访问url繁荣>0占比",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 59 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "1 - sum(deriv(fang_wen_url_fan_rong_bucket{le=\"0.0\"}[5m])>0) / sum(deriv(fang_wen_url_fan_rong_bucket{le=\"+Inf\"}[5m])>0)",
     "legendFormat": "占比"
    }
   ]
  },
  {
   "title": "爬取线程数",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 68 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    { "expr": "sum(pa_qu_xian_cheng_shu)", "legendFormat": "当前" },
    {
     "expr": "sum(pa_qu_xian_cheng_shu_ma_ke_si) > 0",
     "legendFormat": "上限"
    }
   ]
  },
  { "title": "队列", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 77 } },
  {
   "title": "队列积压",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 78 },
   "fieldConfig": { "defaults": { "unit": "locale" } },
   "targets": [
    { "expr": "sum(fa_song_dui_lie_chang_du)", "legendFormat": "当前" },
    {
     "expr": "sum(fa_song_dui_lie_chang_du_ma_ke_si) > 0",
     "legendFormat": "上限"
    }
   ]
  }
 ]
}